services:
  - type: web
    name: renrentube
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: renrentube-db
          property: connectionString

databases:
  - name: renrentube-db
    plan: free
    databaseName: renrentube
    user: renrentube